application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('profileapp.urls'))
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView
from users.views import *

urlpatterns = [
    path('',SignupView.as_view(),name=""),
    path('signup/', SignupView.as_view(),name='signup'),
    path('login/',LoginView.as_view(),name="login"),
    path('index/', HomeView.as_view(), name='index'),
    path('update/', UpdateView.as_view(), name='update'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    
]

profileapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator


class Profile(models.Model):    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(
        max_length=20, 
        validators=[RegexValidator(
                regex=r'^\+?1?\d{9,15}$',
                message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.'
            )],
        null=True
    )
    address = models.TextField(max_length=200, null=True,blank=True)
    profile_img = models.ImageField(default='images/default.jpg', upload_to="images", null=True, blank=True)
    
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"
        
    def __str__(self):
        return f"{self.user.username}'s profile"
    
 

templates/base.html
{% load static %}
<html>
    <head>
        <title>Login Application</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand">LOGIN APPLICATION</a>
            </div>
        </nav>
        {% block content %}
        
        {% endblock content %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
           
    </body>    


</html>    

templates/index.html
{% extends "base.html" %}

{% block content %}


<h2>Welcome {{user.username}}</h2>

<main class="main-container">
    <div class="container">
        <div class="row">
            <div class="col-md-4 profile-photo-container">
                <img src="{{ user.profile.profile_img.url }}" alt="User Image" class="img-fluid rounded-circle" style="max-width: 300px; max-height:500px">
            </div>

            <div class="col-md-8 user-content-container">
                <h2>Name</h2><p class="username">{{user.profile.full_name }}</p>
                <h2>Phone Number</h2><p class="phone_number">{{ user.profile.phone_number }}</p>
                <h2>Address</h2><h2><p class="" style="font-size:20px; font-weight:normal;">{{ user.profile.address }}</p></h2>
                <div class="profile-edit-link-container">
                    <a href="{% url 'profile' %}" class="btn btn-primary">Update Profile</a>
                </div>
            </div>
        </div>
    </div>
</main>

<form class="mt-3">
    {% csrf_token %}
    
    <a href="{% url 'update' %}" class="btn btn-success mr-2">Edit</a>
    <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
</form>


{% endblock content %}

templates/login.html
{% extends "base.html" %}

{% block content%}

<div class="container mt-5">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2>Login</h2>
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-primary" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}

            {{ form }}
            <p>Don't Have a account <a href="{% url 'signup' %}">SIgn Up</a></p>
           
            <button type="submit" class="btn btn-primary">Submit</button>


    </form>
    <br>
</div>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block content%}


<main class="main-container">
    <form class="container" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4 profile-photo-container profile-photo-form-container">
                <p class="profile-page-heading">Edit your profile</p>
                <img src="{{ user.profile.profile_img.url }}" alt="user-image" class="img-fluid rounded-circle" style="max-width: 200px;">
                <div class="form-group mt-3">
                    {{ form.profile_img }}
                </div>
            </div>

            <div class="col-md-8 user-content-container user-profile-form-container">
                <ul class="list-group">
                    <li class="list-group-item">
                        <label for="id_name">Your Name</label>
                        <div class="form-group">
                            {{full_name}}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <label for="id_phone_number">Phone number</label>
                        <div class="form-group">
                            {{ form.phone_number }}
                            {{form.errors}}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <label for="id_address">Address</label>
                        <div class="form-group">
                            {{ form.address }}
                        </div>
                    </li>
                </ul>
                <button type="submit" class="btn btn-primary mt-3">Save</button>
            </div>
        </div>
    </form>
</main>



    {% endblock content %}

templates/signup.html
{% extends "base.html" %}

{% block content%}

<div class="container mt-5">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <h2>Sign Up</h2>
            
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
            {{form}}
            <p>Already Have a account <a href="{% url 'login' %}">Login</a></p>
            <button type="submit" class="btn btn-primary">Signup</button>
    </form>
    <br>
</div>

{% endblock content %}

templates/update.html
{% extends "base.html" %}

{% block content%}

<div class="container mt-5">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <h2>Edit Details</h2>
            
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
            {{form}}
            <br>
            <button type="submit" class="btn btn-primary">Update Detail</button>

    </form>
    <br>
</div>

{% endblock content %}